### ISSUE TITLE
Two sticks in a row

### ISSUE THREAD

**Issue by tompe17** [bobboteck/JoyStick#7] opened 2020-03-02 21:04 UTC
I am trying to place two sticks in a row. I tried putting them in a table but there is something wrong with the input then since the movements are not correct.  I suppose the canvas coordinates might be messed up.

So my question is how can I do what I want to do? It works placing them in div that ends up in two different blocks. Making the divs inline or using span instead of div and it does not work.

**Comment by bobboteck** [comment] 2020-03-03 13:48
Hi @tompe17 can you send me the HTML you use to reproduce the problem, with the table and other solution you have tested?

**Comment by takeru** [comment] 2020-04-01 17:56
https://jsfiddle.net/ssktkr/2mn5uyae/

Please see right one.

**Comment by bobboteck** [comment] 2020-04-10 13:17
Hi @takeru and @tompe17 , I see that the problem is related to the use of TABLE tag, that not work correctly with "offset....." properties of elements.
I try to investigate on this problem, alternatively I can suggest to use DIV structure, in this case all work correctly. I commit a new example page as soon as with two JoyStick in one row.

**Comment by bobboteck** [comment] 2020-04-10 20:08
Ok pushed the example, and you can see in action here http://bobboteck.github.io/joy/joy.html

**Comment by tompe17** [comment] 2020-04-10 21:01
Sorry not getting back on this but I did not have my example easily available since I managed to place them after each other in a way that worked in my app.  But thanks for the example, I will look at it and see if placing it sidwise works better.

**Comment by tompe17** [comment] 2020-04-10 21:11
Looking at your code it seems to be "inline-flex" I missed that it exists.  I tried some inline with div but could not get it to work. But good that it works. I liked this code because it was only javascript and no dependencies on big libraries.

**Comment by jondurrant** [comment] 2020-04-12 07:59
On a mobile device the two joysticks won't work together. The second press makes the relevant joystick follow the first press possition.

**Comment by liamw9534** [comment] 2020-04-15 15:18
I'm running into the same problem as @jondurrant.  I suspect it is because you are not discriminating the location (X,Y) of the touchstart event.  The pressed=1 assignment should only be made for a given JoyStick instance if the (X,Y) happens inside its own canvas area.

**Comment by liamw9534** [comment] 2020-04-17 08:26
Ok, I have a fix for this issue.  Replace the ``onTouchMove`` function as follows:

```
        function onTouchMove(event)
        {
                // Prevent the browser from doing its default thing (scroll, zoom)
                event.preventDefault();
                if(pressed==1 && event.targetTouches[0].target == canvas)
                {
      console.log("move:", canvas.id, ":", event);
                        movedX=event.targetTouches[0].pageX;
                        movedY=event.targetTouches[0].pageY;
                        // Manage offset
                        movedX-=canvas.offsetLeft;
                        movedY-=canvas.offsetTop;
                        // Delete canvas
                        context.clearRect(0, 0, canvas.width, canvas.height);
                        // Redraw object
                        drawExternal();
                        drawInternal();
                }
        }

```

You have to use ``targetTouches`` rather than ``touches``.

**Comment by liamw9534** [comment] 2020-04-17 08:26
Sorry, I added in some ``console.log`` to the code which you can remove.

**Comment by bobboteck** [comment] 2020-04-17 09:42
Hi guys, sorry but this days I'm very busy, I hope to work on this issue in the weekend.

@liamw9534 your suggestion is interesting, but I have the doubt that its works whell only if use one JoyStick at time. You have tested a case of simultaneous use of Stick?

**Comment by liamw9534** [comment] 2020-04-17 09:57
Hello there,

Yes, I tested it with simultaneous sticks (2 side-by-side).  It works well.

Liam.

**Comment by bobboteck** [comment] 2020-04-19 21:26
Hi @liamw9534 , I try your suggestion on my example page http://bobboteck.github.io/joy/joy.html, but I continue to have the problem with the use of the two simultaneos sticks.
I use Chrome on Android, you?

**Comment by liamw9534** [comment] 2020-04-19 22:13
I am using chrome too.  I'll send you my example code tomorrow.

**Comment by liamw9534** [comment] 2020-04-20 08:31
Hi, the attached test code uses GetX and GetY only which is the only methods I am interested in for my project.  Tested using chrome.
[joystick.zip](https://github.com/bobboteck/JoyStick/files/4502133/joystick.zip)

**Comment by bobboteck** [comment] 2020-04-20 12:30
Thanks @liamw9534 , I was not aware of the change to the next lines, now I have modified the code correctly and it works for me too.
As soon as I have some time to spare, I make changes to the code and publish the new version.
Thanks again for the suggestion!

**Comment by liamw9534** [comment] 2020-04-20 12:35
Welcome!  It's a great and useful project so I am glad to help.

**Comment by bobboteck** [comment] 2020-04-21 07:15
Hi @liamw9534 @tompe17 @takeru @jondurrant , I would like if possible to share on the Repository Wiki (even if it is practically empty for now), the projects of those who have used it.
It would be enough to publish a short description, an image, where you can also see the JoyStick, and possibly a link if you have a public repository or a public web page where it is used.
If that's not possible, even a single star to my JoyStick repository is welcome.
Thank you!

**Closed** 2020-04-21 07:20 UTC
Labels: bug, question
